#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "#666666"
bspc config focused_border_color "#888888"
bspc config presel_feedback_color "#55555A"

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         27.99

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config click_to_focus       true
bspc config initial_polarity second_child

bspc rule -a rofi focus=on
bspc rule -a Screenkey manage=off

#Windows key
bspc config super mod4

#Launch Polybar
$HOME/.config/polybar/launch.sh
xss-lock -- betterlockscreen --lock&

setxkbmap -option caps:escape

#Set cursor
xsetroot -cursor_name left_ptr

#Check before running
check_process() {
	echo "$ts: checking $1"
	[ "$1" = "" ]  && return 0
	[ `pgrep -n $1` ] && return 1 || return 0
}

feh --randomize --bg-fill "$HOME/Pictures/Wallpaper/"

#check_process "picom"
#[ $? -eq 0 ] && picom

check_process "redshift"
[ $? -eq 0 ] && redshift

xinput set-button-map 10 1 1 3 4 5 6 7
